from django.urls import path

from . import views

urlpatterns = [
    path("favicon.ico", views.favicon, name="favicon"),
    path("", views.index, name="index"),
    path("docs/", views.documentation, name="documentation"),
    path("docs/getting-started", views.docs_getting_started, name="docs_getting_started"),
    path("contact/", views.contact, name="contact"),
    path("about-modal/", views.about_modal, name="about_modal"),
    path("careers-modal/", views.careers_modal, name="careers_modal"),
    path("careers-modal/", views.careers_modal, name="careers_modal"),

    path("docs/attributes", views.docs_core_attributes, name="docs_core_attributes"),
    path("examples/", views.examples, name="examples"),
    path("examples/<str:filter_name>", views.example_direct, name="example_direct"),
    path("examples/examples-data", views.examples_data, name="examples_data"),
    path("search-examples/<str:filter_name>", views.examples_data, name="examples_data"),
    path("reference_api/", views.reference_api, name="reference"),

    path("demo/data-table-rows", views.data_table_rows, name="data_table_rows"),
    path("demo/live-search-suggestions.html", views.live_search_suggestions, name="live_search_suggestions"),
    path("demo/dynamic-form-validation", views.dynamic_form_validation, name="dynamic_form_validation"),
    path("demo/active-search-results.html", views.active_search_results, name="active_search_results"),
    path("demo/infinite-scroll-items", views.infinite_scroll_items, name="infinite_scroll_items"),
    path("demo/master-detail-detail.html", views.master_detail_detail, name="master_detail_detail"),
    path("demo/click-to-edit-form", views.click_to_edit_form, name="click_to_edit_form"),
    path("demo/click-to-edit-save", views.click_to_edit_save, name="click_to_edit_save"),
    path("demo/click-to-edit-cancel", views.click_to_edit_cancel, name="click_to_edit_cancel"),
    path("demo/dependent-dropdown-options", views.dependent_dropdown_options, name="dependent_dropdown_options"),
    path("demo/tab-content", views.tab_content, name="tab_content"),
    path("demo/lazy-load-image", views.lazy_load_image, name="lazy_load_image"),
    path("demo/delete-row", views.delete_row, name="delete_row"),
    path("demo/progress-bar", views.progress_bar, name="progress_bar"),
    path("demo/modal-dialog-content", views.modal_content, name="modal_content"),
    path("demo/drag-drop-update", views.drag_drop_update, name="drag_drop_update"),
    path("demo/theme-switcher-css", views.theme_switcher, name="theme_switcher"),
    path("demo/calendar-month", views.calendar_month, name="calendar_month"),
    path("demo/polling-fragment", views.polling_example, name="polling_example"),
    path("demo/csv-export", views.csv_export, name="csv_export"),
    path("demo/weather-widget-fragment", views.weather_widget, name="weather_widget"),
    path("demo/markdown-preview-fragment", views.markdown_preview, name="markdown_preview"),
    path("demo/color-picker-fragment", views.color_picker_fragment, name="color_picker_fragment"),
    path("demo/kanban-board-update", views.kanban_board_update, name="kanban_board_update"),
    path("demo/toast-notify", views.toast_notify, name="toast_notify"),
    path("demo/htmx-rest-api", views.htmx_rest_api_demo, name="htmx_rest_api_demo"),
    path("demo/htmx-rest-api.html", views.htmx_rest_api_demo, name="htmx_rest_api_demo_html"),
    path("demo/like-button", views.like_button, name="like_button"),
    path("demo/like-button.html", views.like_button, name="like_button_html"),
    path("demo/live-stock-ticker", views.live_stock_ticker, name="live_stock_ticker"),
    path("demo/live-stock-ticker.html", views.live_stock_ticker, name="live_stock_ticker_html"),
    path("demo/language-switcher", views.language_switcher, name="language_switcher"),
    path("demo/language-switcher.html", views.language_switcher, name="language_switcher_html"),
    path("demo/sort-table.html", views.sort_table, name="sort_table"),

    path("demo/<str:page_name>", views.dynamic_page, name="examples"),
]
